### ISSUE TITLE
Where will open-source development be coordinated or where should I post proposals for tools?

### ISSUE THREAD

**Issue by matoushybl** [knurling-rs/meta#6]
Hi,
I've been using the tools for a while and I am extremely happy with them! During the development however I came across a few ideas about extensions / new tools that could also be developed or added to existing tooling.
These ideas are for example:
Sending data from probe-run via UDP to other applications - usable for data plotting etc.
Time profiling using defmt - with correct timestamping of messages we could measure how much time is spent in functions with very low cost which could be useful for tracking for example how much time is spent in interrupt handlers.
Some kind of a "logic analyzer" for showing event timelines - like seeing when interrupt was fired, etc.

I was going to start implementing at least the first part as I believe that adding some way to consume the data produced by probe-run is vital for further tooling improvement, but I figured it would be better to ask here first, I believe that @jamesmunns had some kind of visualization based on defmt already developed, but I don't know the current state of it.

Thank you very much for these awesome tools!

**Comment by Lotterleben** [comment]
Hi Matous,
thank you for opening this issue–i t actually sparked a discussion across the knurling team and we've decided to dedicate this repos' Issues section to exactly these discussions (and to gauge interest in future tools, etc) :)

**Comment by Urhengulas** [comment]
@Lotterleben Is this decision documented somehwere? Couldn't find it in a  quick search.

**Comment by Urhengulas** [comment]
Oh well, the following section in the README actually resembles it.
> To discuss new features and ideas, get involved in the Issues section of this repository.

I consider this solved by https://github.com/knurling-rs/meta/commit/302d201b4e464d2e33caf535c2b4a3efdc8b23af.

**Comment by Urhengulas** [comment]
@matoushybl Feel free to open an issue about a specific tool/feature you would love to see!
